# Project information
site_name: 'GildanPractice'
site_description: 'Practica Profesional Universitaria'
site_author: 'Andrik Santos'
site_url: 'https://andriksantos.github.io/GildanPractice/'

# Repository
repo_name: 'AndrikSantos/GildanPractice'
repo_url: 'https://github.com/andriksantos/GildanPractice'

# Copyright
copyright: 'Copyright &copy; 2019 - Andrik Santos'

# Configuration
pages:
  - Práctica Profesional Universitaria: index.md
theme:
  name: 'material'
  language: 'es'
  palette:
    primary: 'Blue'
    accent: 'Indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
extra:
  social:
    - type: globe
      link: https://andriksantos.github.io
    - type: github-alt
      link: https://github.com/andriksantos
    - type: twitter
      link: https://twitter.com/andrik_rsm
    - type: linkedin
      link: https://www.linkedin.com/in/andriksantos
    - type: facebook
      link: https://www.facebook.com/andrik.rsm
    - type: instagram
      link: https://www.instagram.com/andriksantos12/

# Google Analytics
google_analytics:
  - 'UA-103804510-1'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true